### ISSUE TITLE
SSR custom directive not working with router-link.

### ISSUE THREAD

**Issue by DaxChen** [intlify/vue-i18n-extensions#1]
### vue & vue-i18n version
vue@2.5.13 (with nuxt@1.3.0)
vue-i18n@7.4.2
vue-i18n-extension@0.1.0

### Reproduction Link
[Online Demo](https://daxchen.github.io/vue-i18n-ssr-directive-bug/)
[Github Repo](https://github.com/DaxChen/vue-i18n-ssr-directive-bug)

### Steps to reproduce
Open the online demo link:
1. refresh without cache (command-shift-R on mac) and see that `{{ $t('xxx') }}` shows immediately (SSR) but `v-t="'xxx'"` shows a bit later (no SSR)
2. Right-click and "View page source", and you can see this:

```html
<router-link class="curly_bracket">{{ $t('curly_bracket') }}</router-link>
<router-link class="directive" v-t="'directive'" />
```

renders to:

```html
<a class="curly_bracket">Using {{ }}, shows in SSR!</a>
<a class="directive"></a>
```

Only `{{ $t() }}` is server side rendered, `v-t="'xxx"` isn't.

This SSR directive works with primitive html tags, but when using with vue components such as `<router-link>`, it fails.

### What is Expected?

`v-t` directive on `<router-link>` to work with SSR

### What is actually happening?

`v-t` directive only works with primitive html elements, but not with vue components such as `<router-link>`.

Thank you so much!

**Comment by kazupon** [comment]
Hmm 🤔 , I seem same the below issue:
https://github.com/vuejs/vue/issues/5239

**Comment by kazupon** [comment]
Maybe, custom directive doesn't not support for components on SSR.
However, functional component work on SSR.

**Comment by kazupon** [comment]
close (in-activity)
