### ISSUE TITLE
add example for vue-cli

### ISSUE THREAD

**Issue by kazupon** [intlify/vue-i18n-extensions#5]
- vue-loader v15 later
- vue-cli v3 ref: https://github.com/kazupon/vue-i18n/blob/dev/examples/perf/compiler/vue.config.js

**Comment by lucaswerkmeister** [comment]
I think this was done in 1ff910be48b8f95a0bb8758d0ebffe1a3000960e? Or at least, the second code block in https://github.com/intlify/vue-i18n-extensions#pre-translation-with-using-v-t-custom-directive looks similar to vue-cli config to me.

**Comment by kazupon** [comment]
Thank you for your feedback!
You're right!
So, close
